name: Update README with Version

on:
  push:
    branches:
      - main  # Adjust this based on your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from aces.vromfs.bin_u/version
        id: get_version
        run: |
          VERSION=$(cat aces.vromfs.bin_u/version)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Extract current version from README.md
        id: readme_version
        run: |
          # Extract the version from the README.md file (assuming it follows "Version: x.x.x" format)
          CURRENT_VERSION=$(grep -oP '(?<=Version: )\d+\.\d+\.\d+' README.md)
          echo "Current version in README.md: $CURRENT_VERSION"
          echo "::set-output name=current_version::$CURRENT_VERSION"

      - name: Check if README.md needs updating
        id: check_readme
        run: |
          if [ "$CURRENT_VERSION" = "$VERSION" ]; then
            echo "README is already up to date."
            echo "::set-output name=needs_update::false"
          else
            echo "README needs to be updated."
            echo "::set-output name=needs_update::true"
          fi

      - name: Update README.md with version
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          # Replace the current version in README.md with the new version
          sed -i "s/Version: $CURRENT_VERSION/Version: $VERSION/g" README.md

      - name: Commit changes
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
