name: Update README with Version

on:
  push:
    paths:
      - "aces.vromfs.bin_u/version"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract last version from README
      id: get_last_version
      run: |
        LAST_VERSION=$(grep -oP 'Current Version: \K[0-9.]+' README.md || echo "N/A")
        echo "::set-output name=last_version::$LAST_VERSION"

    - name: Get current version from version file
      id: get_version
      run: |
        NEW_VERSION=$(cat aces.vromfs.bin_u/version)
        echo "::set-output name=new_version::$NEW_VERSION"



    - name: Update README with new and last version
      run: |
        # Write new README with updated version
        awk '/Current Version:/ {print "Current Version: '"${{ steps.get_version.outputs.new_version }}"'"; next}1' README.md > temp.md
        mv temp.md README.md
        
        # Append last version
        if grep -q "Last Version" README.md; then
          awk '/Last Version:/ {print "Last Version: '"${{ steps.get_last_version.outputs.last_version }}"'"; next}1' README.md > temp.md
        else
          echo "Last Version: ${{ steps.get_last_version.outputs.last_version }}" >> README.md
        fi
        mv temp.md README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with new version"
        git push
