# .github/workflows/use-reusable-workflow.yml
name: Use Reusable Version Store Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual execution

jobs:
  use-reusable-workflow:
    uses: AzayakaHoshi/actions_priv/.github/workflows/action.yml@main  # Replace with your actual repo path
    with:
      token: ${{ secrets.P_A_T }}  # Use a Personal Access Token stored as a secret in your repo
