# .github/workflows/use-reusable-workflow.yml
name: Use Reusable Version Store Workflow

on: [push]

jobs:
  use-reusable-workflow:
    uses: AzayakaHoshi/actions_priv/.github/workflows/action.yml@main  # Replace with your actual repo path
    with:
      token: ${{ secrets.PAT_TOKEN }}  # Use a Personal Access Token stored as a secret in your repo
