name: Update README with Version

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from aces.vromfs.bin_u/version
        id: get_version
        run: |
          if [ ! -f aces.vromfs.bin_u/version ]; then
            echo "Version file not found!"
            exit 1
          fi
          VERSION=$(cat aces.vromfs.bin_u/version)
          if [ -z "$VERSION" ]; then
            echo "Version file is empty!"
            exit 1
          fi
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Check if README.md needs updating
        id: check_readme
        run: |
          if ! grep -q "Current Version:" README.md; then
            echo "Current Version line not found in README.md!"
            exit 1
          fi
          CURRENT_VERSION=$(grep -Po '(?<=Current Version: )[0-9.]+' README.md)
          echo "Current README version: $CURRENT_VERSION"
          if [ "$CURRENT_VERSION" = "$VERSION" ]; then
            echo "README is already up to date with version $VERSION."
            echo "::set-output name=needs_update::false"
          else
            echo "README needs to be updated. Current version is $CURRENT_VERSION, new version is $VERSION."
            echo "::set-output name=needs_update::true"
          fi

      - name: Update README.md with new version
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          echo "Updating README.md with version $VERSION"
          sed -i "s/Current Version: [0-9.]*/Current Version: $VERSION/" README.md
          cat README.md  # Display the updated README for debugging

      - name: Commit changes
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
