name: "Run Private Action"

on: [push]

jobs:
  call-reusable-workflow:
    uses: AzayakaHoshi/actions_priv/.github/workflows/action.yml@main  # Reference the reusable workflow
    with:
      secret-token: ${{ secrets.P_A_T }}  # Use the PAT stored in the secret
