name: "Run Private Action"

on: [push]

jobs:
  run-private-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run private action
        run: |
        AzayakaHoshi/actions_priv/.github/workflows/action.yml@main
        with:
          secret-token: ${{ secrets.P_A_T }}  # Use the PAT stored in the secret
