# .github/workflows/use-private-action.yml
name: "Run Private Action"

on: [push]

jobs:
  run-private-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run private action
        uses: AzayakaHoshi/actions_priv
        with:
          secret-token: ${{ secrets.P_A_T }}
