name: Update README with Version

on:
  push:
    paths:
      - "aces.vromfs.bin_u/version"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup
    - id: setup
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull

    - name: Get new version from version file
      id: get_new_version
      run: |
        NEW_VERSION=$(cat aces.vromfs.bin_u/version)
        echo "New Version: $NEW_VERSION"
        echo "::set-output name=new_version::$NEW_VERSION"

    - name: Create or read current version from version_store.txt
      id: get_last_version
      run: |
        if [ ! -f version_store.txt ]; then
          echo "Unknown" > version_store.txt
        fi
        LAST_VERSION=$(cat version_store.txt)
        echo "Last Version: $LAST_VERSION"
        echo "::set-output name=last_version::$LAST_VERSION"

    - name: Update README with new and last version
      run: |
        NEW_VERSION=${{ steps.get_new_version.outputs.new_version }}
        LAST_VERSION=${{ steps.get_last_version.outputs.last_version }}

        # Update Current Version in README.md
        sed -i "s/Current Version:.*/Current Version: $NEW_VERSION<br>/" README.md

        # Add or update Last Version
        if grep -q "Last version:" README.md; then
          sed -i "s|<sub>.*Last version:.*</sub>|<sub>*Last version: $LAST_VERSION*</sub><br>|" README.md
        else
          echo "<sub>*Last version: $LAST_VERSION*</sub><br>" >> README.md
        fi

    - name: Update version_store.txt with new version
      run: |
        echo "${{ steps.get_new_version.outputs.new_version }}" > version_store.txt

    - name: Commit changes
      run: |
        git add README.md version_store.txt
        git commit -m "Update README with new version and store current version"
        git push
