name: Update README with Version

on:
  push:
    branches:
      - main  # Adjust this based on your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from aces.vromfs.bin_u/version
        id: get_version
        run: |
          if [ ! -f aces.vromfs.bin_u/version ]; then
            echo "Version file not found!"
            exit 1
          fi
          VERSION=$(cat aces.vromfs.bin_u/version)
          if [ -z "$VERSION" ]; then
            echo "Version file is empty!"
            exit 1
          fi
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Check if README.md needs updating
        id: check_readme
        run: |
          # Debugging: Ensure the README file exists
          if [ ! -f README.md ]; then
            echo "README.md not found!"
            exit 1
          fi
          
          # Debugging: Output the first 10 lines of README.md to ensure it's being read
          echo "README.md content preview:"
          head -n 10 README.md
          
          # Try to extract the current version
          CURRENT_VERSION=$(grep -Po '(?<=\[)[0-9.]+' README.md || true)
          
          # If no current version is found, output a message
          if [ -z "$CURRENT_VERSION" ]; then
            echo "No version found in README.md."
            echo "::set-output name=needs_update::true"
          else
            echo "Current README version: $CURRENT_VERSION"
            if [ "$CURRENT_VERSION" = "$VERSION" ]; then
              echo "README is already up to date with version $VERSION."
              echo "::set-output name=needs_update::false"
            else
              echo "README needs to be updated. Current version is $CURRENT_VERSION, new version is $VERSION."
              echo "::set-output name=needs_update::true"
            fi
          fi

      - name: Update README.md with new version
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          echo "Updating README.md with version $VERSION"
          # Replace the version inside the link [version](aces.vromfs.bin_u/version)
          sed -i "s/\[[0-9.]*\](aces.vromfs.bin_u\/version)/\[$VERSION\](aces.vromfs.bin_u\/version)/" README.md
          cat README.md  # Display the updated README for debugging

      - name: Commit changes
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with version $VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
