name: "Trigger Private Repository Workflow"

on:
  push:
      paths:
       - 'aces.vromfs.bin_u/**'
  workflow_dispatch:

jobs:
  trigger-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.P_A_T }}" \
          https://api.github.com/repos/AzayakaHoshi/actions_priv/dispatches \
          -d '{"event_type":"trigger-update-version-store"}'
