name: Update README Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (optional, in case using node script)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Extract version and update README
      id: update_version
      run: |
        # Define variables
        VERSION_FILE="aces.vromfs.bin_u/version"
        README_FILE="README.md"
        
        # Extract version number from file
        VERSION=$(cat $VERSION_FILE)

        # Replace the placeholder in the README file
        sed -i "s/\[.*\](aces.vromfs.bin_u\/version)/[$VERSION](aces.vromfs.bin_u\/version)/" $README_FILE

        # Output version for testing step
        echo "::set-output name=version::$VERSION"

        # Confirm change
        echo "Updated README.md with version $VERSION"

    - name: Test if README contains the correct version
      run: |
        # Retrieve the version from the previous step
        VERSION=${{ steps.update_version.outputs.version }}
        
        # Verify if README contains the updated version link
        if grep -q "\[$VERSION\](aces.vromfs.bin_u/version)" README.md; then
          echo "README contains the correct version link."
        else
          echo "README does not contain the correct version link."
          exit 1
        fi

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if README has changes
        if [ -n "$(git status --porcelain)" ]; then
          git add README.md
          git commit -m "Update version in README to $VERSION"
          git push
        else
          echo "No changes to commit."
