name: "Trigger Private Repository Workflow"

on:
  push:
    branches:
      - main  # This will trigger on pushes to the main branch of the public repo

jobs:
  trigger-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PRIVATE_REPO_PAT }}" \
          https://api.github.com/repos/AzayakaHoshi/actions_priv/dispatches \
          -d '{"event_type":"trigger-update-version-store"}'
